apiVersion: v1
kind: Service
metadata:
  name: projects-service
  namespace: default
  labels:
    app: projects
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  selector:
    app: projects