apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  namespace: default
  labels:
    app: discovery-server
spec:
  type: ClusterIP
  ports:
    - protocol: "TCP"
      port: 8761
      targetPort: 8761
  selector:
    app: discovery-server